### ISSUE TITLE
how to create images from a php class

### ISSUE THREAD

**Issue by fabbrikk** [letrunghieu/favicon#1]
Hi, there a way to generate images from a php class and not from the command line?

**Comment by letrunghieu** [comment]
Hi, the current version of package just support generating images from the command line only. However, you can see the [source code of the command line](https://github.com/letrunghieu/favicon/blob/master/src/GenerateCommand.php) to make your own class.

**Comment by fabbrikk** [comment]
Thanks. Done and works very well!
